In [1]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn import preprocessing

np.random.seed(30)

In [2]:
C = 3 #number of classes
threshold_value = 0.75

Loading data

In [3]:
def load_homework3():
    file_name = '../bayes_datasets/estudante_201706840076_train.txt'
    my_data = np.genfromtxt(file_name, delimiter=',')
    X = my_data[:,:3] # 3 features
    y = np.ravel(my_data[:,3:],order='C') #convert column vector into 1D array
    return X,y

def load_simple():
    #from numpy import genfromtxt
    my_data = np.genfromtxt('../../datasets/simple.csv', delimiter=',')
    X = my_data[:,:2] # fish length and weight
    y = np.ravel(my_data[:,2:],order='C') #convert column vector into 1D array
    return X,y

Choose here the dataset

In [4]:
if True:
    #X,y = load_simple()
    X,y = load_simple()
    x_test = X #test with train set
    K = X.shape[1] #number of features
    y_test = y
else:
    N = 3000 #number of training examples
    K = 4 #number of features
    max_feature_value = 10
    X = np.random.randint(max_feature_value, size = (N, K)) #3000 x 4 matrix with elements [0, 9]
    y = np.random.randint(C, size = (N,))
    x_test = np.random.randint(max_feature_value, size = (1, K))
    y_test = np.array([0]) #random class

In [5]:
print('Original input features:')
print(X)
print('True labels:')
print(y)

Original input features:
[[12.   3.2]
 [10.   0.5]
 [14.   2.8]
 [14.   2.4]
 [13.   1.8]
 [13.8  1.5]
 [11.   1. ]]
True labels:
[0. 1. 0. 0. 1. 0. 1.]


In [6]:
#Make it mean=0 and variance=1
scaler = preprocessing.StandardScaler().fit(X)
print('Original means:', scaler.mean_)
print('Original standard deviations:', scaler.scale_)
X_scaled = scaler.transform(X)
print('Scaled (standardized) input features:')
print(X_scaled)

Original means: [12.54285714  1.88571429]
Original standard deviations: [1.47246843 0.90147272]
Scaled (standardized) input features:
[[-0.3686715   1.45793177]
 [-1.72693492 -1.53716719]
 [ 0.98959192  1.0142134 ]
 [ 0.98959192  0.57049504]
 [ 0.31046021 -0.09508251]
 [ 0.85376558 -0.42787128]
 [-1.04780321 -0.98251924]]


In [7]:
BNBclf = BernoulliNB(alpha=1.0, binarize=threshold_value, fit_prior=True)
BNBclf.fit(X_scaled, y)
print(BNBclf)

BernoulliNB(binarize=0.75)


In [8]:
print('#Report:')
binarized_features =np.asarray(X_scaled > threshold_value, dtype=int)
print('binarized_features and their labels:\n',np.concatenate((binarized_features, np.reshape(y,(len(y),1))), axis=1))
print('class_count_',BNBclf.class_count_)
print('### Priors:')
print('class_log_prior_ (natural log)', BNBclf.class_log_prior_)
estimated_priors = np.exp(BNBclf.class_log_prior_)
print('class_prior_', estimated_priors, 'and their sum=',np.sum(estimated_priors))
print('### Features')
print('feature_count_ (Dimension: classes x features):\n',BNBclf.feature_count_)
print('feature_log_prob_',BNBclf.feature_log_prob_)
estimated_feature_prob = np.exp(BNBclf.feature_log_prob_)
print('estimated_feature_prob',estimated_feature_prob)
print('### Predictions using training set as test set')
print('predictions=',(BNBclf.predict(x_test)))
print('predict_log_proba=',(BNBclf.predict_log_proba(x_test)))
print('predict_proba=',(BNBclf.predict_proba(x_test)))
print('score (fraction of correct predictions)=',(BNBclf.score(x_test,y_test)))

#Report:
binarized_features and their labels:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
class_count_ [4. 3.]
### Priors:
class_log_prior_ (natural log) [-0.55961579 -0.84729786]
class_prior_ [0.57142857 0.42857143] and their sum= 1.0
### Features
feature_count_ (Dimension: classes x features):
 [[3. 2.]
 [0. 0.]]
feature_log_prob_ [[-0.40546511 -0.69314718]
 [-1.60943791 -1.60943791]]
estimated_feature_prob [[0.66666667 0.5       ]
 [0.2        0.2       ]]
### Predictions using training set as test set
predictions= [0. 0. 0. 0. 0. 0. 0.]
predict_log_proba= [[-0.0861777  -2.4941233 ]
 [-0.3074847  -1.32913595]
 [-0.0861777  -2.4941233 ]
 [-0.0861777  -2.4941233 ]
 [-0.0861777  -2.4941233 ]
 [-0.0861777  -2.4941233 ]
 [-0.0861777  -2.4941233 ]]
predict_proba= [[0.91743119 0.08256881]
 [0.73529412 0.26470588]
 [0.91743119 0.08256881]
 [0.91743119 0.08256881]
 [0.91743119 0.08256881]
 [0.91743119 0.08256881]
 [0.91743119 0.08256881]]
score (frac