<a target="_blank" href="https://colab.research.google.com/github/aldebaro/ml-ufpa/blob/main/nb_dos_caras_safos/Decision_stump/ml_601_decision_stump.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

**Decision Stump**

_This code implements a Decision Stump as a DecisionTreeClassifier of depth = 1._

_Aldebaro. 2020-12-19._

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
import numpy as np
import os

### Loading data
Make sure the dataset path is correct.

In [2]:
def load_dataset():
    #from numpy import genfromtxt
    with open('../../datasets/lista1_dataset.csv', 'r') as arquivo:
        my_data = np.genfromtxt(arquivo, delimiter=',')

    X = my_data[:,:2] # two first parameters are input vector
    #y = my_data[:,2:]
    y = np.ravel(my_data[:,2:],order='C') #convert column vector into 1D array
    return X,y

X, y = load_dataset()
print('datasets:')
print(X)
print('Labels:')
print(y)

datasets:
[[ 4.  -1. ]
 [-3.   2. ]
 [ 2.   0. ]
 [ 1.3 -2. ]
 [ 2.2 -1. ]
 [ 3.2  0. ]
 [ 0.   5.2]
 [-1.   5.3]]
Labels:
[0. 0. 1. 1. 0. 1. 0. 0.]


In [3]:
input_dimension = X.shape
if len(input_dimension) != 2:
    raise Exception('Input must be 2D')
num_features = input_dimension[1]
for k in range(num_features):
    print('feature', k, ', values and corresponding labels')
    sorted_indices = np.argsort(X[:,k])
    print(X[sorted_indices,k])
    print(y[sorted_indices])

feature 0 , values and corresponding labels
[-3.  -1.   0.   1.3  2.   2.2  3.2  4. ]
[0. 0. 0. 1. 1. 0. 1. 0.]
feature 1 , values and corresponding labels
[-2.  -1.  -1.   0.   0.   2.   5.2  5.3]
[1. 0. 0. 1. 1. 0. 0. 0.]


In [4]:
#Below is an example about how to use weights for each sample in the training set
sample_weight = np.ones(y.shape, dtype=float)
#sample_weight[0] = 1000 #in this case we put more weigth on feature_0

decision_stump = DecisionTreeClassifier(max_depth=1, min_samples_leaf=1,criterion='gini')
decision_stump.fit(X, y, sample_weight)

print('\nThe fitted decision stump:')
r = export_text(decision_stump) #, feature_names=feature_names) #, class_names=target_names)
print(r)

print('correct labels=',y)
print('   predictions=',(decision_stump.predict(X)))


The fitted decision stump:
|--- feature_1 <= 1.00
|   |--- class: 1.0
|--- feature_1 >  1.00
|   |--- class: 0.0

correct labels= [0. 0. 1. 1. 0. 1. 0. 0.]
   predictions= [1. 0. 1. 1. 1. 1. 0. 0.]
